Updates virtualenv getting started commands (docs)
googleapis/python-artifact-registry pull request #66
Opened 2021-08-18 19:12 UTC by Phuurl

`venv` is included in all versions of Python that the library supports - this small PR updates the getting started info in the README to use the builtin version of `venv` rather that requiring users to install the additional `virtualenv` package - the additional features of which are not used in the guide, or generally required (and system `pip` calls can cause issues if the user's permissions/path are not set correctly).

Also updates the `pip install` call to be relative, as after venv activation it should resolve to the venv's instance, making the path unnecessary.

Not opened an issue as this is such a minor PR, however can if required.
🦕

2021-08-20 21:51 UTC, dandhlee requested changes
Thanks for putting this together! Could you also update other mentions for `virtualenv` above in the README?

2021-08-20 21:57 UTC, dinagraves commented
Thank you! Can confirm this works by default in Cloud Shell.

2021-08-20 21:58 UTC, dinagraves approved these changes

2021-08-22 06:18 UTC, dandhlee approved these changes
LGTM.

2021-08-22 06:23 UTC, dandhlee commented
`docs` prefix will trigger a patch version release.

2021-08-22 06:25 UTC, merged